#!/usr/bin/env bash
#
# Turn the console MCP server on, or take it back.
#
#     sudo /opt/mudhorn/deploy/enable-console.sh            # on, named ops only
#     sudo /opt/mudhorn/deploy/enable-console.sh --shell    # on, arbitrary argv too
#     sudo /opt/mudhorn/deploy/enable-console.sh --off      # off, token kept
#     sudo /opt/mudhorn/deploy/enable-console.sh --status    # what is set now
#     sudo /opt/mudhorn/deploy/enable-console.sh --rotate   # new token, same state
#
# ## What this grants, stated plainly before you run it
#
# A **root** process on the trading box that runs commands, reachable over HTTP
# on 127.0.0.1:8788, gated by one bearer token. Published to the internet it is
# one secret away from a shell on the machine holding the Alpaca keys.
#
# That is a bigger grant than anything else in `deploy/`. `enable-forge.sh` lets
# the settings agent move one number in one file; this runs `deploy/update.sh`,
# `systemctl` and `journalctl`. It is a separate script for exactly that reason
# and must not be folded into another one.
#
# ## What bounds it
#
# - **No trading credential and no route to one.** `console_mcp.py` imports none
#   of broker, risk, journal, models, reconcile, grants or mcp_server, and
#   `tests/test_console_mcp.py` parses the AST and fails the build if that
#   changes. `place_order` is a different process reached a different way.
# - **Six named operations**, each a fixed argv. `run_command` is not registered
#   at all without `--shell`, so a caller cannot see it to try.
# - **argv lists, never shell strings**, so `&&`, `|`, `>` and `$(...)` are
#   unreachable even with `--shell`.
# - **A token of at least 32 characters, or the server refuses to start.**
#
# ## Why a script rather than four commands in the README
#
# The same reason as `enable-forge.sh`: the realistic moment somebody runs this
# is from a phone, one-handed, in a web console — the moment a long paste loses
# a line. And one of the steps generates a secret, which must not end up in a
# shell history, a provisioning log or a screenshot. `bootstrap.sh` deliberately
# does not create the token file, because a token generated by a provisioning
# script is a token in a provisioning log.

set -euo pipefail

APP_DIR="${APP_DIR:-/opt/mudhorn}"
ENV_FILE="/etc/mudhorn-console.env"
UNIT="mudhorn-console.service"
PORT=8788

MODE="on"
WANT_SHELL=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --shell) WANT_SHELL=1 ;;
    --off) MODE="off" ;;
    --status) MODE="status" ;;
    --rotate) MODE="rotate" ;;
    -h|--help) sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

if [[ $EUID -ne 0 ]]; then
  echo "Run with sudo: sudo $0" >&2
  exit 1
fi

say() { printf '%s\n' "$*"; }

# ------------------------------------------------------------------- status

if [[ "$MODE" == "status" ]]; then
  say "console:"
  if [[ -f "$ENV_FILE" ]]; then
    # The VALUE is never printed, here or anywhere. Same rule as the Settings
    # page and the startup banner: configured or not configured, never the
    # secret. This output is the kind of thing that gets pasted into a chat.
    if grep -q '^MUDHORN_CONSOLE_TOKEN=.\{32,\}$' "$ENV_FILE"; then
      say "  token       set, at least 32 characters"
    else
      say "  token       PRESENT BUT TOO SHORT — the server will refuse to start"
    fi
    if grep -q '^MUDHORN_CONSOLE_SHELL=1$' "$ENV_FILE"; then
      say "  run_command ENABLED — arbitrary argv is reachable with the token"
    else
      say "  run_command off — six named operations only"
    fi
    say "  file        $ENV_FILE ($(stat -c '%a %U:%G' "$ENV_FILE"))"
  else
    say "  token       not set ($ENV_FILE does not exist)"
  fi
  say "  unit        $(systemctl is-enabled "$UNIT" 2>/dev/null || echo 'not enabled') / $(systemctl is-active "$UNIT" 2>/dev/null || echo 'inactive')"
  say ""
  say "  Reachable from outside only if something forwards to 127.0.0.1:$PORT."
  say "  Check with: tailscale funnel status"
  exit 0
fi

# ---------------------------------------------------------------------- off

if [[ "$MODE" == "off" ]]; then
  systemctl disable --now "$UNIT" 2>/dev/null || true
  say "Stopped and disabled $UNIT."
  say ""
  say "The token file is KEPT, so turning it back on does not invalidate a"
  say "connector you have already configured. Remove it deliberately:"
  say "    sudo rm $ENV_FILE"
  say ""
  say "**A Funnel outlives this.** systemd stopping the service does not"
  say "withdraw the public URL, and a URL pointing at a closed port is a URL"
  say "that starts working again the moment somebody restarts the unit. Take"
  say "the Funnel down too:"
  say "    sudo tailscale funnel --https=443 off"
  exit 0
fi

# ------------------------------------------------------- token, on or rotate

if [[ ! -f "$APP_DIR/.venv/bin/electrum-bot-console" ]]; then
  echo "electrum-bot-console is not installed at $APP_DIR/.venv/bin/." >&2
  echo "Run: sudo $APP_DIR/deploy/bootstrap.sh" >&2
  exit 1
fi

NEW_TOKEN=""
if [[ "$MODE" == "rotate" || ! -f "$ENV_FILE" ]]; then
  if ! command -v openssl >/dev/null 2>&1; then
    echo "openssl is not installed, and a token is not worth improvising." >&2
    echo "  apt-get install -y openssl" >&2
    exit 1
  fi
  NEW_TOKEN="$(openssl rand -hex 32)"

  # Written with a restrictive umask so the file is never briefly world
  # readable between creation and chmod.
  OLD_UMASK="$(umask)"
  umask 077
  {
    echo "# Mudhorn console MCP server. Read by mudhorn-console.service."
    echo "# Deliberately NOT in /opt/mudhorn/.env: that file holds the broker"
    echo "# keys, and keeping the console's credential separate means its blast"
    echo "# radius is stated by which file leaked rather than inferred."
    echo "MUDHORN_CONSOLE_TOKEN=$NEW_TOKEN"
  } > "$ENV_FILE"
  umask "$OLD_UMASK"
fi

chmod 600 "$ENV_FILE"
chown root:root "$ENV_FILE"

# The shell flag is rewritten every run so the state is what the flags say,
# rather than accumulating whatever a previous run left behind.
sed -i '/^MUDHORN_CONSOLE_SHELL=/d' "$ENV_FILE"
if [[ $WANT_SHELL -eq 1 ]]; then
  echo "MUDHORN_CONSOLE_SHELL=1" >> "$ENV_FILE"
fi

systemctl daemon-reload
systemctl enable --now "$UNIT"

sleep 2
if ! systemctl is-active --quiet "$UNIT"; then
  systemctl status "$UNIT" --no-pager --lines=20 || true
  echo "" >&2
  echo "$UNIT did not start. Nothing is exposed." >&2
  exit 1
fi

say "Console is running on 127.0.0.1:$PORT/mcp."
if [[ $WANT_SHELL -eq 1 ]]; then
  say "run_command is ENABLED: arbitrary argv is reachable with this token."
else
  say "run_command is off. Six named operations only."
fi
say ""

if [[ -n "$NEW_TOKEN" ]]; then
  say "TOKEN (shown once, and only here):"
  say ""
  say "    $NEW_TOKEN"
  say ""
  say "Copy it now. It is not printed again — re-read $ENV_FILE or --rotate."
  say "It is a bearer token: anyone holding it can run these operations as root."
  say "Do not paste it into a chat, an issue or a screenshot."
  say ""
fi

say "To reach it from Claude, publish it and add it as a connector:"
say ""
say "    sudo tailscale funnel --bg $PORT"
say "    tailscale funnel status          # note the https:// URL"
say ""
say "Then at claude.ai -> Settings -> Connectors -> Add custom connector:"
say "    URL     <that URL>/mcp"
say "    Header  Authorization: Bearer <the token above>"
say ""
say "Turn it all off with:"
say "    sudo $0 --off"
say "    sudo tailscale funnel --https=443 off"
