#!/usr/bin/env python3
"""Compare the pinned reference repos against their latest upstream releases.

Reads reference/registry.yaml and reference/versions.json, asks the GitHub API
what each project's newest release and newest default-branch commit are, and
regenerates reference/STATUS.md.

STATUS.md is committed, so running this periodically turns upstream drift into a
reviewable git diff: you can see at a glance which projects moved, when they last
released, and how far behind the local pin is.

Usage:
    python scripts/check_reference_updates.py
    GITHUB_TOKEN=ghp_... python scripts/check_reference_updates.py   # higher rate limit

Unauthenticated GitHub API access is limited to 60 requests/hour, which is enough
for this registry but not for repeated runs. Set GITHUB_TOKEN if you hit it.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY = REPO_ROOT / "reference" / "registry.yaml"
VERSIONS = REPO_ROOT / "reference" / "versions.json"
STATUS = REPO_ROOT / "reference" / "STATUS.md"

API = "https://api.github.com"
TIMEOUT = 20


def api_get(path: str) -> Any | None:
    """GET a GitHub API path. Returns None on 404, raises on other failures."""
    request = urllib.request.Request(
        f"{API}{path}",
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "electrum-bot-reference-checker",
            **(
                {"Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}"}
                if os.environ.get("GITHUB_TOKEN")
                else {}
            ),
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=TIMEOUT) as response:
            return json.loads(response.read())
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return None
        raise


def upstream_state(repo: str) -> dict[str, Any]:
    """Latest release (or tag) plus latest default-branch commit for one repo."""
    state: dict[str, Any] = {"repo": repo}

    meta = api_get(f"/repos/{repo}")
    if meta is None:
        state["error"] = "repository not found"
        return state

    state["stars"] = meta.get("stargazers_count")
    state["license"] = (meta.get("license") or {}).get("spdx_id")
    state["archived"] = meta.get("archived", False)
    default_branch = meta.get("default_branch", "main")
    state["default_branch"] = default_branch

    release = api_get(f"/repos/{repo}/releases/latest")
    if release:
        state["latest_release"] = release.get("tag_name")
        state["latest_release_date"] = (release.get("published_at") or "")[:10]
    else:
        # Plenty of active projects never cut GitHub releases; fall back to tags.
        tags = api_get(f"/repos/{repo}/tags?per_page=1")
        if tags:
            state["latest_release"] = tags[0].get("name")
            state["latest_release_date"] = None
        else:
            state["latest_release"] = None
            state["latest_release_date"] = None

    commits = api_get(f"/repos/{repo}/commits?sha={default_branch}&per_page=1")
    if commits:
        head = commits[0]
        state["head_commit"] = head["sha"]
        state["head_commit_date"] = (
            head.get("commit", {}).get("committer", {}).get("date", "")
        )[:10]

    return state


def render(rows: list[dict[str, Any]], checked_at: str, fetched_at: str | None) -> str:
    lines: list[str] = [
        "# Reference library status",
        "",
        "Generated by `scripts/check_reference_updates.py` — do not edit by hand.",
        "",
        f"- Last checked upstream: **{checked_at}**",
        f"- Local clones last fetched: **{fetched_at or 'never'}** "
        "(`scripts/fetch_reference.py`)",
        "",
        "`Pinned` is the commit in `reference/versions.json`, i.e. what is actually "
        "in `reference/src/`. `Upstream HEAD` is the newest commit on the default "
        "branch. When they differ, re-run the fetch script to move the pin, and "
        "commit the diff.",
        "",
    ]

    if rows and all(r.get("error") for r in rows):
        lines += [
            "> Every row errored. If these are `403 Forbidden`, the GitHub API is "
            "blocked by a network or egress policy rather than anything being wrong "
            "with the registry — re-run from an unrestricted network. If they are "
            "`403 rate limit exceeded`, set `GITHUB_TOKEN` and try again.",
            "",
        ]

    lines += [
        "| Project | Licence | Pinned | Pinned date | Upstream HEAD | Upstream date "
        "| Latest release | Status |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for row in rows:
        name = row["name"]
        pinned = (row.get("pinned_commit") or "")[:7] or "—"
        upstream = (row.get("head_commit") or "")[:7] or "—"
        licence = row.get("license") or row.get("license_detected") or "—"
        release = row.get("latest_release") or "—"
        release_date = row.get("latest_release_date")
        release_cell = f"{release} ({release_date})" if release_date else release

        if row.get("error"):
            status = f"error: {row['error']}"
        elif row.get("archived"):
            status = "archived upstream"
        elif not row.get("pinned_commit"):
            status = "not fetched yet"
        elif row.get("head_commit") and row["pinned_commit"] != row["head_commit"]:
            status = "behind"
        elif row.get("head_commit"):
            status = "current"
        else:
            status = "unknown"

        lines.append(
            f"| [{name}]({row.get('url', '')}) | {licence} | `{pinned}` | "
            f"{row.get('pinned_date') or '—'} | `{upstream}` | "
            f"{row.get('head_commit_date') or '—'} | {release_cell} | {status} |"
        )

    lines += [
        "",
        "## Why each project is here",
        "",
    ]
    for row in rows:
        why = " ".join((row.get("why") or "").split())
        lines.append(f"- **{row['name']}** (`{row.get('repo', '?')}`) — {why}")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    with REGISTRY.open() as f:
        registry = yaml.safe_load(f).get("repos", [])

    pinned: dict[str, Any] = {}
    fetched_at: str | None = None
    if VERSIONS.exists():
        data = json.loads(VERSIONS.read_text())
        fetched_at = data.get("fetched_at")
        pinned = {r["name"]: r for r in data.get("repos", [])}

    rows: list[dict[str, Any]] = []
    for entry in registry:
        name = entry["name"]
        local = pinned.get(name, {})
        row: dict[str, Any] = {
            "name": name,
            "repo": entry["repo"],
            "url": entry["url"],
            "why": entry.get("why", ""),
            "pinned_commit": local.get("commit"),
            "pinned_date": (local.get("commit_date") or "")[:10] or None,
            "license_detected": local.get("license_detected"),
        }
        print(f"  checking {entry['repo']} ...")
        try:
            row.update(upstream_state(entry["repo"]))
        except Exception as e:  # network/policy failures should not lose the report
            row["error"] = f"{type(e).__name__}: {e}"[:200]
        rows.append(row)

    checked_at = datetime.now(UTC).isoformat(timespec="seconds")
    STATUS.write_text(render(rows, checked_at, fetched_at))
    print(f"\nWrote {STATUS}")

    behind = [r["name"] for r in rows if r.get("head_commit") and r.get("pinned_commit") and r["pinned_commit"] != r["head_commit"]]
    errors = [r["name"] for r in rows if r.get("error")]
    if behind:
        print(f"Behind upstream: {', '.join(behind)}")
    if errors:
        print(f"Could not check: {', '.join(errors)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
